/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppSearchRouteImport } from './routes/app.search'
import { Route as AppPlayAnythingRouteImport } from './routes/app.play-anything'
import { Route as AppLibraryRouteImport } from './routes/app.library'
import { Route as AppPlaylistIdRouteImport } from './routes/app.playlist.$id'
import { Route as AppArtistIdRouteImport } from './routes/app.artist.$id'
import { Route as AppAlbumIdRouteImport } from './routes/app.album.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppPlayAnythingRoute = AppPlayAnythingRouteImport.update({
  id: '/play-anything',
  path: '/play-anything',
  getParentRoute: () => AppRoute,
} as any)
const AppLibraryRoute = AppLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AppRoute,
} as any)
const AppPlaylistIdRoute = AppPlaylistIdRouteImport.update({
  id: '/playlist/$id',
  path: '/playlist/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppArtistIdRoute = AppArtistIdRouteImport.update({
  id: '/artist/$id',
  path: '/artist/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppAlbumIdRoute = AppAlbumIdRouteImport.update({
  id: '/album/$id',
  path: '/album/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/library': typeof AppLibraryRoute
  '/app/play-anything': typeof AppPlayAnythingRoute
  '/app/search': typeof AppSearchRoute
  '/app/': typeof AppIndexRoute
  '/app/album/$id': typeof AppAlbumIdRoute
  '/app/artist/$id': typeof AppArtistIdRoute
  '/app/playlist/$id': typeof AppPlaylistIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/library': typeof AppLibraryRoute
  '/app/play-anything': typeof AppPlayAnythingRoute
  '/app/search': typeof AppSearchRoute
  '/app': typeof AppIndexRoute
  '/app/album/$id': typeof AppAlbumIdRoute
  '/app/artist/$id': typeof AppArtistIdRoute
  '/app/playlist/$id': typeof AppPlaylistIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/library': typeof AppLibraryRoute
  '/app/play-anything': typeof AppPlayAnythingRoute
  '/app/search': typeof AppSearchRoute
  '/app/': typeof AppIndexRoute
  '/app/album/$id': typeof AppAlbumIdRoute
  '/app/artist/$id': typeof AppArtistIdRoute
  '/app/playlist/$id': typeof AppPlaylistIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/app/library'
    | '/app/play-anything'
    | '/app/search'
    | '/app/'
    | '/app/album/$id'
    | '/app/artist/$id'
    | '/app/playlist/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app/library'
    | '/app/play-anything'
    | '/app/search'
    | '/app'
    | '/app/album/$id'
    | '/app/artist/$id'
    | '/app/playlist/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/app/library'
    | '/app/play-anything'
    | '/app/search'
    | '/app/'
    | '/app/album/$id'
    | '/app/artist/$id'
    | '/app/playlist/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/search': {
      id: '/app/search'
      path: '/search'
      fullPath: '/app/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/play-anything': {
      id: '/app/play-anything'
      path: '/play-anything'
      fullPath: '/app/play-anything'
      preLoaderRoute: typeof AppPlayAnythingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/library': {
      id: '/app/library'
      path: '/library'
      fullPath: '/app/library'
      preLoaderRoute: typeof AppLibraryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/playlist/$id': {
      id: '/app/playlist/$id'
      path: '/playlist/$id'
      fullPath: '/app/playlist/$id'
      preLoaderRoute: typeof AppPlaylistIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/artist/$id': {
      id: '/app/artist/$id'
      path: '/artist/$id'
      fullPath: '/app/artist/$id'
      preLoaderRoute: typeof AppArtistIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/album/$id': {
      id: '/app/album/$id'
      path: '/album/$id'
      fullPath: '/app/album/$id'
      preLoaderRoute: typeof AppAlbumIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppLibraryRoute: typeof AppLibraryRoute
  AppPlayAnythingRoute: typeof AppPlayAnythingRoute
  AppSearchRoute: typeof AppSearchRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAlbumIdRoute: typeof AppAlbumIdRoute
  AppArtistIdRoute: typeof AppArtistIdRoute
  AppPlaylistIdRoute: typeof AppPlaylistIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppLibraryRoute: AppLibraryRoute,
  AppPlayAnythingRoute: AppPlayAnythingRoute,
  AppSearchRoute: AppSearchRoute,
  AppIndexRoute: AppIndexRoute,
  AppAlbumIdRoute: AppAlbumIdRoute,
  AppArtistIdRoute: AppArtistIdRoute,
  AppPlaylistIdRoute: AppPlaylistIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
